---
- name:  create  pool adel-common-443-pool at common
  hosts: all
  connection: local

 vars:
    f5_provider:
      password: "vish123"
      user: "vish"
      server: "{{ ansible_host }}"
      validate_certs: no
      server_port: 443
  
  
  tasks:
  - name: create a pool
    bigip_pool:
      provider: "{{ f5_provider }}"
      description: "this is adel-common-443-pool"
      partition: common
      lb_method: round-robin
      pool: adel1-common-8443-pool
      state: present