---
- name:  create  partition 
  hosts: all
  connection: local
  
  vars:
    f5_provider:
      password: "vish123"
      user: "vish"
      server: "{{ ansible_host }}"
      validate_certs: no
      server_port: 443
  
  tasks:
  - name: Create partition "VCC1" 
    bigip_partition:
      name: VCC1
      provider: "{{f5_provider}}"
  - name: Create partition "VCC2" 
    bigip_partition:
      name: VCC2
      provider: "{{f5_provider}}"
  - name: Create partition "VCC4" 
    bigip_partition:
      name: VCC4
      provider: "{{f5_provider}}"