---
- name:  Create HTTP,HTTPS,FTP  Monitor-VCC1-VCC2-VCC3-VCC4
  hosts: all
  connection: local

  vars:
    f5_provider:
      password: "networkjourney"
      user: "admin"
      server: "{{ ansible_host }}"
      validate_certs: no
      server_port: 443
  tasks:
  - name: Create HTTP Monitor_VCC1
    bigip_monitor_http:
     state: present
     name: VCC1_http_monitor
     provider: "{{ f5_provider }}"
     partition: VCC1
  - name: Create HTTP Monitor_VCC2
    bigip_monitor_http:
     state: present
     name: VCC2_http_monitor
     provider: "{{ f5_provider }}"
     partition: VCC2
  - name: Create HTTP Monitor_VCC3
    bigip_monitor_http:
     state: present
     name: VCC3_http_monitor
     provider: "{{ f5_provider }}"
     partition: VCC3
  - name: Create HTTP Monitor_VCC4
    bigip_monitor_http:
     state: present
     name: VCC4_http_monitor
     provider: "{{ f5_provider }}"
     partition: VCC4
     
  - name: Create HTTPS Monitor_VCC1
    bigip_monitor_https:
     state: present
     name: VCC1_https_monitor
     provider: "{{ f5_provider }}"
     partition: VCC1
  - name: Create HTTPS Monitor_VCC2
    bigip_monitor_https:
     state: present
     name: VCC2_https_monitor
     provider: "{{ f5_provider }}"
     partition: VCC2
  - name: Create HTTPS Monitor_VCC3
    bigip_monitor_https:
     state: present
     name: VCC3_https_monitor
     provider: "{{ f5_provider }}"
     partition: VCC3
  - name: Create HTTPS Monitor_VCC4
    bigip_monitor_https:
     state: present
     name: VCC4_https_monitor
     provider: "{{ f5_provider }}"
     partition: VCC4
