---
- name:  Create VLANS
  hosts: all
  connection: local

  vars:
    f5_provider:
      password: "networkjourney"
      user: "admin"
      server: "{{ ansible_host }}"
      validate_certs: no
      server_port: 443
  tasks:
  - name: Create Self IP
    bigip_selfip:
     address: 10.10.10.10
     name: VCC-01A-VLAN3099-SELF-IP
     netmask: 255.255.255.0
     vlan: 3099
     provider: "{{ f5_provider }}"
  - name: Create Self IP
    bigip_selfip:
     address: 20.20.20.20
     name: VCC-01A-VLAN501-SELF-IP
     netmask: 255.255.255.0
     vlan: 501
     provider: "{{ f5_provider }}"
  - name: Create Self IP
    bigip_selfip:
     address: 30.30.30.30
     name: VCC-01B-VLAN717-SELF-IP
     netmask: 255.255.255.0
     vlan: 717
     provider: "{{ f5_provider }}"
  - name: Create Self IP
    bigip_selfip:
     address: 40.40.40.40
     name: VCC-01B-VLAN717-SELF-IP
     netmask: 255.255.255.0
     vlan: 718
     provider: "{{ f5_provider }}"
