---
- name:  create  node
  hosts: all
  connection: local

  vars:
    f5_provider:
      password: "networkjourney"
      user: "admin"
      server: "{{ ansible_host }}"
      validate_certs: no
      server_port: 443
  
  
  tasks:
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      host: "6.6.6.36" 
      name: "vcc-36.eu"
      partition:"VCC1"
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      host: "6.6.6.37" 
      name: "vcc-37.eu"
      partition:"VCC1"
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      hhost: "6.6.6.38" 
      name: "vcc-38.eu"
      partition:"VCC1"
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      host: "6.6.6.39" 
      name: "vcc-39.eu"
      partition:"VCC1"
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      host: "6.6.6.40" 
      name: "vcc-40.eu"
      partition:"VCC1"
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      host: "6.6.6.41" 
      name: "vcc-41.eu"
      partition:"VCC1"
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      host: "6.6.6.42" 
      name: "vcc-42.eu"
      partition:"VCC1"
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      host: "6.6.6.43" 
      name: "vcc-43.eu"
      partition:"VCC1"
  
      
