---
- name:  create  pool
  hosts: all
  connection: local

  vars:
    f5_provider:
      password: "networkjourney"
      user: "admin"
      server: "{{ ansible_host }}"
      validate_certs: no
      server_port: 443
  tasks:
    - name: add members to the above created pool
      bigip_pool_member:
       provider: "{{ f5_provider }}"
       description: "webserver {{ item.name }}"
       host: "{{ item.host }}"
       name: "{{ item.name }}"
       partition: "VCC1"
       pool: adel-VCC1-443-pool
       port: 443
      with_items:
       - host: 6.6.6.25
         name: vcc-25.eu
       - host: 6.6.6.26
         name: vcc-26.eu
       - host: 6.6.6.27
         name: vcc-27.eu
       - host: 6.6.6.28
         name: vcc-28.eu
       - host: 6.6.6.29
         name: vcc-29.eu
       - host: 6.6.6.30
         name: vcc-30.eu
    - name: add members to the above created pool
      bigip_pool_member:
       provider: "{{ f5_provider }}"
       description: "webserver {{ item.name }}"
       partition: "VCC2"
       host: "{{ item.host }}"
       name: "{{ item.name }}"
       pool: adel-VCC2-8443-pool
       port: 443
      with_items:
       - host: 5.5.5.25
         name: vcc-25.eu
       - host: 5.5.5.26
         name: vcc-26.eu
       - host: 5.5.5.27
         name: vcc-27.eu
       - host: 5.5.5.28
         name: vcc-28.eu
       - host: 5.5.5.29
         name: vcc-29.eu
       - host: 5.5.5.30
         name: vcc-30.eu
    - name: add members to the above created pool
      bigip_pool_member:
       provider: "{{ f5_provider }}"
       description: "webserver {{ item.name }}"
       partition: "VCC3"
       host: "{{ item.host }}"
       name: "{{ item.name }}"
       pool: adel-VCC3-80-pool
       port: 443
      with_items:
       - host: 4.4.4.25
         name: vcc-25.eu
       - host: 4.4.4.26
         name: vcc-26.eu
       - host: 4.4.4.27
         name: vcc-27.eu
       - host: 4.4.4.28
         name: vcc-28.eu
       - host: 4.4.4.29
         name: vcc-29.eu
       - host: 4.4.4.30
         name: vcc-30.eu
    - name: add members to the above created pool
      bigip_pool_member:
       provider: "{{ f5_provider }}"
       description: "webserver {{ item.name }}"
       partition: "VCC4"
       host: "{{ item.host }}"
       name: "{{ item.name }}"
       pool: adel-VCC4-8080-pool
       port: 443
      with_items:
       - host: 3.3.3.25
         name: vcc-25.eu
       - host: 3.3.3.26
         name: vcc-26.eu
       - host: 3.3.3.27
         name: vcc-27.eu
       - host: 3.3.3.28
         name: vcc-28.eu
       - host: 3.3.3.29
         name: vcc-29.eu
       - host: 3.3.3.30
         name: vcc-30.eu
    
