---
- name:  create  partition 
  hosts: all
  connection: local

  vars:
    f5_provider:
      password: "networkjourney"
      user: "admin"
      server: "{{ ansible_host }}"
      validate_certs: no
      server_port: 443
  tasks:
   - name: create partition
     bigip_partition:
        provider:"{{f5_provider}}"
        name: VCC1
        password: "networkjourney"
        user: "admin"
 
  
