---
- name:  create  node
  hosts: all
  connection: local
  vars:
    f5_provider:
      password: "networkjourney"
      user: "admin"
      server: "{{ ansible_host }}"
      validate_certs: no
      server_port: 443
  tasks:
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      partition: VCC1
      host: "6.6.6.36" 
      name: "vcc-36.eu"
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      partition: VCC1
      host: "6.6.6.37" 
      name: "vcc-37.eu"
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      partition: VCC1
      host: "6.6.6.38" 
      name: "vcc-38.eu"
  - name: CREATE NODES
    bigip_node:
      provider: "{{f5_provider}}"
      partition: VCC1
      host: "6.6.6.39" 
      name: "vcc-39.eu"
  
      
